name: Master branch push and pull(merge) requests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run unit tests and build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: unpack firebase file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$API_KEYS_SECRET" --output networkstore/src/main/java/com/zywczas/networkstore/utils/Constants.kt networkstore/src/main/java/com/zywczas/networkstore/utils/Constants.kt.gpg
        env:
          API_KEYS_SECRET: ${{ secrets.API_KEYS_SECRET }}
      - name: Unit test
        run: bash ./gradlew testDebugUnitTest --stacktrace
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 10