name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: unpack firebase file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$API_KEYS_SECRET" --output networkstore/src/main/java/com/zywczas/networkstore/utils/Constants.kt networkstore/src/main/java/com/zywczas/networkstore/utils/Constants.kt.gpg
      env:
        API_KEYS_SECRET: ${{ secrets.API_KEYS_SECRET }}
    - name: test
      run: bash ./gradlew testDebugUnitTest --stacktrace